apiVersion: v1
kind: ConfigMap
metadata:
  name: warptail-configmap
data:
  config.yaml: |
    tailscale:
      api_key: ""
      hostnmae: "TS_HOSTNAME"
    dashboard:
      enabled: true
      username: admin
      password: CHANGEME
